#ifndef MYSCANCODES_H
#define MYSCANCODES_H

#define SPECIAL_OFFSET 0x88
#define SPECIAL_CHARS_NO 57

char* specialKeyNames[SPECIAL_CHARS_NO] =
{
	"enter",
	"esc",
	"bkspace",
	"tab",
	"space",
	"caps",
	"f1",
	"f2",
	"f3",
	"f4",
	"f5",
	"f6",
	"f7",
	"f8",
	"f9",
	"f10",
	"f11",
	"f12",
	"prsc",
	"sclk",
	"pause",
	"insert",
	"home",
	"pgup",
	"delete",
	"end",
	"pgdown",
	"right",
	"left",
	"down",
	"up",
	"numlock",
	"gr/",
	"gr*",
	"gr-",
	"gr+",
	"grenter",
	"gr1",
	"gr2",
	"gr3",
	"gr4",
	"gr5",
	"gr6",
	"gr7",
	"gr8",
	"gr9",
	"gr0",
	"grdot",
	"app",
	"lctrl",
	"lshift",
	"lalt",
	"lwin",
	"rctrl",
	"rshift",
	"ralt",
	"rwin"
};

unsigned char specialKeyCodes[SPECIAL_CHARS_NO] =
{
	0x28 + SPECIAL_OFFSET,
	0x29 + SPECIAL_OFFSET,
	0x2A + SPECIAL_OFFSET,
	0x2B + SPECIAL_OFFSET,
	0x2C + SPECIAL_OFFSET,
	0x39 + SPECIAL_OFFSET,
	0x3A + SPECIAL_OFFSET,
	0x3B + SPECIAL_OFFSET,
	0x3C + SPECIAL_OFFSET,
	0x3D + SPECIAL_OFFSET,
	0x3E + SPECIAL_OFFSET,
	0x3F + SPECIAL_OFFSET,
	0x40 + SPECIAL_OFFSET,
	0x41 + SPECIAL_OFFSET,
	0x42 + SPECIAL_OFFSET,
	0x43 + SPECIAL_OFFSET,
	0x44 + SPECIAL_OFFSET,
	0x45 + SPECIAL_OFFSET,
	0x46 + SPECIAL_OFFSET,
	0x47 + SPECIAL_OFFSET,
	0x48 + SPECIAL_OFFSET,
	0x49 + SPECIAL_OFFSET,
	0x4A + SPECIAL_OFFSET,
	0x4B + SPECIAL_OFFSET,
	0x4C + SPECIAL_OFFSET,
	0x4D + SPECIAL_OFFSET,
	0x4E + SPECIAL_OFFSET,
	0x4F + SPECIAL_OFFSET,
	0x50 + SPECIAL_OFFSET,
	0x51 + SPECIAL_OFFSET,
	0x52 + SPECIAL_OFFSET,
	0x53 + SPECIAL_OFFSET,
	0x54 + SPECIAL_OFFSET,
	0x55 + SPECIAL_OFFSET,
	0x56 + SPECIAL_OFFSET,
	0x57 + SPECIAL_OFFSET,
	0x58 + SPECIAL_OFFSET,
	0x59 + SPECIAL_OFFSET,
	0x5A + SPECIAL_OFFSET,
	0x5B + SPECIAL_OFFSET,
	0x5C + SPECIAL_OFFSET,
	0x5D + SPECIAL_OFFSET,
	0x5E + SPECIAL_OFFSET,
	0x5F + SPECIAL_OFFSET,
	0x60 + SPECIAL_OFFSET,
	0x61 + SPECIAL_OFFSET,
	0x62 + SPECIAL_OFFSET,
	0x63 + SPECIAL_OFFSET,
	0x65 + SPECIAL_OFFSET,
	0x80,
	0x81,
	0x82,
	0x83,
	0x84,
	0x85,
	0x86,
	0x87
};

#endif
